name: Deploy to Deno Deploy

on:
  push:
    branches:
      - main # 或者你想要触发部署的分支

env:
  OVERSEAS: ${{ secrets.OVERSEAS }} # 使用GitHub Secrets来存储环境变量

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy with Deno Deploy
      uses: denoland/deployctl@v1
      with:
        project: meting # 这里要改成你的Deno Deploy的project的name
        entrypoint: deno.js
